version: 2.1

# Setting up dependencies for use by the jobs in this project
executors:
  docker-executor:
    docker:
      - image: cimg/base:2020.01

commands:
  load-dependecies:
    steps:
      - run:
          name: Install aws-cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Set up aws cred
          command: |
            aws configure set aws_access_key_id "${CI_INFRA_BOT_AWS_ACCESS_KEY}"
            aws configure set aws_secret_access_key "${CI_INFRA_BOT_AWS_SECRET_KEY}"
            aws configure set default.region "eu-west-1"
      - run:
          name: Install Terraform
          command: |
            git clone https://github.com/tfutils/tfenv.git ~/.tfenv
            echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
            mkdir -p ~/.local/bin/
            . ~/.profile
            ln -s ~/.tfenv/bin/* ~/.local/bin
            tfenv install
            tfenv use

# Define the jobs we want to run for this project
jobs:
  build-dependencies:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - load-dependecies
      - run:
          name: Inititialise and Validate
          command: |
            terraform init
            terraform validate
  build-plan:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - load-dependecies
      - attach_workspace:
          at: .
      - run:
          name: prepare deploy
          command: |
            mkdir /tmp/output/
            terraform init
            terraform plan \
              -input=false \
              -out=/tmp/output/tfplan \
              -no-color \
              --var-file environments/dev.tfvars
      - store_artifacts:
          path: /tmp/output/
          destination: review-plan
      - persist_to_workspace:
          root: /tmp/output/
          paths:
            - tfplan
  deploy-plan:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - load-dependecies
      - attach_workspace:
          at: .
      - run:
          name: deploy
          command: |
            terraform init
            terraform apply -input=false tfplan

# Orchestrate our job run sequence
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-dependencies
      - build-plan:
          requires: 
            - build-dependencies
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - hold-for-approval:
          type: approval
          requires:
            - build-plan
      - deploy-plan:
          requires: 
            - hold-for-approval
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
